### ISSUE TITLE
TV series in Plex is marked as watched when it shouldn’t 

### ISSUE THREAD

**Issue by charlieny100** [luigi311/JellyPlex-Watched#132]
I am set up to sync watched status from Plex to Jellyfin and not the other way around. When I run the script, one tv series gets marked as watched in Plex. The logs show each episode is marked as watched. All the other shows are fine.

I’m running this on unraid.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem ideally with DEBUG set to true, be sure to remove sensitive information

**Type:**
- [ ] Docker Compose
- [ ] Docker
- [x] Unraid
- [ ] Native

**Additional context**

**Comment by luigi311** [comment]
interesting its weird that that was happening, i did run into an issue recently with some of my matching logic that uses filenames to match if the filenames are named something generic like S01E01.mkv since theres no unique identifier such as the name of the show. I added in a fix for this in the dev branch, can you give that a test? Should be as simple as changing your unraid docker from pointing to :latest to :dev

**Comment by luigi311** [comment]
Ohh i see what you mean, yeah i run into that constantly, i sync both ways and if i try rewatch an old series i usually unmark it in plex or jellyfin depending on what im watching on and then forget to mark it on the other side so jellyplex-watched remarks it for me trying to be helpful lol.

If you are only going from plex to jellyfin did you set SYNC_FROM_JELLYFIN_TO_PLEX to false? That should solve your issue if you dont care about going from jellyfin to plex.

**Comment by charlieny100** [comment]
For my initial test I wanted to sync only from Plex to Jellyfin. But after I was comfortable with it I changed it to sync in both directions. I find myself using Jellyfin more than I thought. Jellyfin was going to be my backup solution. If Jellyfin had an Apple TV client that would let me skip intros I would probably stop using Plex.
