### ISSUE TITLE
Syntax error main.py line 25

### ISSUE THREAD

**Issue by thatnovaguy** [luigi311/JellyPlex-Watched#15]
I'm getting a syntax error when trying to run main.py
`  File "main.py", line 25
    logger(f"User {user_1} and {user_other} not found in watched list 2", 1)
                                                                       ^
SyntaxError: invalid syntax`

I'm sorry if I'm missing something obvious.

**Comment by luigi311** [comment]
What version of python are you using? Ive only tested this with python 3.10 and i think im using features that are exclusive to python 3.6+

**Comment by luigi311** [comment]
I just confirmed via vermin that this does require python 3.6. 

I ran the script via python 2 and it reports the exact same error so it looks like your system is defaulting to python 2 instead of python 3. You can try running python3 main.py and see if that works. If that still doesnt work you can install the latest python 3 for windows or update python via your package manager and see if that has 3.6 or higher. If neither of those options are available you will have to use the docker container.
