### ISSUE TITLE
[Feature Request] Unraid docker template

### ISSUE THREAD

**Issue by PutzJimmy** [luigi311/JellyPlex-Watched#52]
If possible make a Unraid docker template for this or add a snippet in the install guide how to set it up without a template on Unraid

**Comment by luigi311** [comment]
That's probably a good idea, I've been using this on my unraid server but since it was still in rapid development i never made an official template or anything and just manually set it up. I'll go ahead and look into how to submit something to the unofficial repository for unraid that way its a lot easier.

**Comment by PutzJimmy** [comment]
[This](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084) might help get you started =)

**Comment by luigi311** [comment]
I have submitted the request to Squid so it will hopefully be looked at soon and added. Here is the xml in question in case you want to give it a go while you wait since im not sure how long it takes for squid to look at it and approve it since im sure they are swamped with requests.

https://github.com/luigi311/unraid-templates/blob/main/JellyPlex-Watched.xml

**Comment by PutzJimmy** [comment]
Awesome =) thx a ton

**Comment by luigi311** [comment]
This is now in the unraid community application store. There was an issue with the logfile directory not existing since i was using a mapped folder in my testing so i updated the template to store the logfile in /tmp so it should be fixed and working in the app store within 2 hours or so.

**Comment by PutzJimmy** [comment]
Very nice, gonna give it a spin tonight =)
