### ISSUE TITLE
[Feature Request] - Sync unplayed status

### ISSUE THREAD

**Issue by Hydranet** [luigi311/JellyPlex-Watched#85]
**Is your feature request related to a problem? Please describe.**
No my feature request is not related to a problem

**Describe the solution you'd like**
I would like to the sync also to be able to sync unplayed status, so that if you mark a movie to status unplayed on Plex it will also sync it to unplayed status on Jellyfin/Emby and vice-versa.

**Describe alternatives you've considered**
I haven't considered any alternative solutions because I only found one other script that does the same and yours is easier to user and has multi-user support.

**Additional context**
I just came across this script today and I just wanted to say thank your the work you do on this script!! I also wanted to let you know I run Plex, Emby and Jellfyin. I also tested the sync from  Plex to Emby since [issue 56](https://github.com/luigi311/JellyPlex-Watched/issues/56) the person hadn't test it yet since they hadn't responded since their last reply.  I just wanted to let you know the watched sync play status from Plex to Emby and vice-versa works as well even though it's not officially supported yet.

**Comment by luigi311** [comment]
Unfortunately the way the script is setup it simply does a check for things that are partially or fully watched and sync them over. It doesn't search for things that were watched and are now unwatched so theres no way to handle things. Its very simple in what it does. I need to check to see what other user data there is to see if there might be a timestamp of changed status and do a comparison to see which status to do but that would complicate the process since it would require a comparison and then implement the logic to mark unwatched. It would also run into problems with the fact that you can sync multiple servers so all the servers would have to be checked prior to marking anything so the latest timestamp is actually used, partially watched probably also runs into this issue though I haven't tested it and it probably eventually resolves itself after multiple runs are done as it propagates partial watched statuses backwards through the servers.

**Comment by Hydranet** [comment]
That does sound complicated! If it's too much work than you can close this feature request because I'm already quite happy that I am able to sync watched status, it would have been the cherry on top of the cake if it would have been possible.
